# problem 2 a

In [1]:
import numpy as np
from numpy import *
from sklearn.decomposition import PCA,NMF

import pandas as pd
from sklearn import preprocessing
from sklearn import model_selection
import math
import matplotlib.pyplot as plt
from matplotlib import colors
from sklearn import metrics
%matplotlib inline

data_txt=[]
f = open('colleges.txt')
for i in range(1303):
    line = f.readline()
    line = line.strip()
    listFromLine = line.split('\t')
    m=[]
    j=0
    for k in listFromLine:
        if i==0:
            m.append(k)
        elif j==0:
            m.append(k)
            j+=1
        else:
            if k=='':
                k=np.NAN
            m.append(float(k))
            
    data_txt.append(m)
df = pd.DataFrame(data=data_txt[1:],columns=data_txt[0])
print(df.shape)
print(df.columns)
df=df.dropna(axis=0,how='any')
print(df.shape)
college=df[['college name']]
df.drop(['college name'], axis=1, inplace=True)
data=df
print(data.shape)
data_n = preprocessing.normalize(data)

(1302, 18)
Index(['college name', 'apps received', 'apps accepted', 'new stud enrolled',
       '% new stud from top 10%', '% new stud from top 25%',
       'num FT undergrad', 'num PT undergrad', 'in-state tuition',
       'out-of-state tuition', 'room', 'board', 'add fees', 'est book costs',
       'est personal costs', '% fac with PHD', 'stud:fac ratio',
       'graduation rate'],
      dtype='object')
(471, 18)
(471, 17)


# problem 2 b

In [12]:
data_n=np.array(data_n)

for i in range(1,10):
    pca = PCA(n_components=i,random_state=9)
    Y=pca.fit_transform(data_n)
    k=sum(pca.explained_variance_ratio_)
    if k>0.95:
        print('the number of component is',i)
        print(pca.explained_variance_ratio_)
        print(pca.singular_values_)
        print(pca.components_[0:3,:])
         
        break
for i in range(3):
    for j in range(17):
        if pca.components_[i][j]>0.35:
            print(i,j)
        
    

the number of component is 5
[ 0.78569491  0.07833391  0.05024888  0.02432843  0.02065389]
[ 7.79985719  2.46283083  1.9725267   1.37251393  1.26462175]
[[  3.79727828e-01   2.54619260e-01   1.12652005e-01  -2.02588186e-04
    2.25002725e-04   5.83190681e-01   1.32116971e-01  -5.86907263e-01
   -2.69000893e-01   8.91916973e-03  -5.26965190e-03   2.75574609e-02
    7.04590879e-03   5.45761652e-02   1.45946206e-03   5.41263943e-04
   -5.68136312e-05]
 [ -4.01035089e-01  -1.81624793e-01  -8.35780168e-03  -1.77739550e-04
    4.41009791e-03  -2.45335499e-02   1.55013154e-01  -4.81956591e-01
    4.29015161e-01   3.16090298e-01   3.07525230e-01   1.07722851e-01
    1.13116401e-01   3.82127038e-01   1.24834200e-02   4.09500171e-03
    6.98337621e-03]
 [ -6.55161792e-01  -2.24457333e-01   4.22947359e-02  -1.09874978e-03
   -2.64352060e-03   4.28481173e-01   2.94552157e-01   1.54902979e-01
   -3.95514658e-01  -2.12703585e-01  -7.83551804e-02  -1.21014254e-01
   -2.35823563e-02   3.44357055e-02  

In [24]:
print('important features by PCA are')
for i in [0,5,8,13]:
    print(df.columns[i])

important features by PCA are
apps received
num FT undergrad
out-of-state tuition
est personal costs


# problem 2 c

In [63]:
# if no normalization
data=np.array(data)
for i in range(1,10):
    pca1 = PCA(n_components=i,random_state=9)
    Y1=pca1.fit_transform(data)
    k=sum(pca1.explained_variance_ratio_)
    if k>0.95:
        print('the number of component is',i)
        print(pca1.explained_variance_ratio_)
        print(pca1.singular_values_)
        break

the number of component is 3
[ 0.56136974  0.36452432  0.03496909]
[ 161098.37646782  129816.50756696   40207.66348017]


# problem 2 d

In [27]:
model = NMF(n_components=3, init='random', random_state=9)
W = model.fit_transform(data_n)
H = model.components_
NMF_origin=model.inverse_transform(W)
NMF_s_error=metrics.mean_squared_error(data_n,NMF_origin)*417*17
print('NMF squared error is',NMF_s_error)
print(H)
for i in range(3):
    for j in range(17):
        if H[i][j]>0.8:
            print(i,j)
PCA_origin=pca.inverse_transform(Y)
PCA_s_error=metrics.mean_squared_error(data_n,PCA_origin)*417*17
print('PCA squared error is',PCA_s_error)            

NMF squared error is 8.3490597287
[[  2.18693450e-01   1.37969976e-01   2.65206793e-02   7.80270072e-03
    1.47182630e-02   0.00000000e+00   0.00000000e+00   3.50497639e+00
    3.21553316e+00   5.73935943e-01   5.72465621e-01   5.40343474e-02
    1.35799630e-01   2.57540251e-01   1.70678498e-02   2.91479646e-03
    1.79578140e-02]
 [  2.11664361e+00   1.34434058e+00   5.01921832e-01   3.60111565e-03
    4.44578924e-03   2.49256040e+00   3.85029369e-01   0.00000000e+00
    1.87560372e-01   2.54281677e-02   0.00000000e+00   2.96483788e-02
    0.00000000e+00   0.00000000e+00   2.37860227e-03   0.00000000e+00
    2.38173913e-03]
 [  0.00000000e+00   4.82624818e-02   6.93609387e-02   1.55682299e-03
    7.27579056e-03   3.33860473e-01   1.97580112e-01   0.00000000e+00
    9.35141930e-01   4.06783246e-01   3.78391206e-01   1.25022849e-01
    1.27057242e-01   4.06066616e-01   1.54948577e-02   4.35802739e-03
    1.00266987e-02]]
0 7
0 8
1 0
1 1
1 5
2 8
PCA squared error is 2.79289880217


In [25]:
print('important features by NMF are')
for i in [0,1,5,7,8]:
    print(df.columns[i])

important features by NMF are
apps received
apps accepted
num FT undergrad
in-state tuition
out-of-state tuition
